apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER 
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-initdb
          configMap:
            name: postgres-initdb-config
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  init.sql: |
    CREATE SCHEMA IF NOT EXISTS bookstore;
    CREATE TABLE friends (id INT, name VARCHAR(256), age INT, gender VARCHAR(3));
    CREATE TABLE IF NOT EXISTS bookstore.book (id serial primary key, name text not null, year int not null, author text not null);
    INSERT INTO bookstore.book
    (name, author, year)
    VALUES
    ('Terry Pratchett, Otec prasátek', 'Bill Kaye, Stephen Player', 2007),
    ('TERRY PRATCHETT DISCWORLD NOVEL COLLECTION.', 'TERRY. PRATCHETT', 2012),
    ('Terry Pratchett''s Discworld Coloring Book', 'Terry Pratchett', 2017),
    ('Sourcery', 'Terry Pratchett', 2014),
    ('Dodger', 'Terry Pratchett', 2019),
    ('Seriously Funny', 'Terry Pratchett', 2016),
    ('Nation', 'Terry Pratchett', 2009),
    ('The Carpet People', 'Terry Pratchett', 2015),
    ('Truckers', 'Terry Pratchett', 2015),
    ('Sekáč', 'Terry Pratchett, Jan Kantůrek', 2011);
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

