apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookstore-api
  name: bookstore-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bookstore-api
  type: NodePort
status:
  loadBalancer: {}
